# Generated by Django 5.1.5 on 2025-04-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('overtime_pay', models.FloatField(blank=True, null=True)),
                ('allowance', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
