# Generated by Django 5.1.5 on 2025-05-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='overtime_pay',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
